# Generated by Django 4.2 on 2026-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alllog',
            name='unique_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
