# Generated by Django 4.2 on 2026-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0003_staffadmin_alter_alllog_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffadmin',
            name='block',
        ),
        migrations.RemoveField(
            model_name='staffadmin',
            name='district',
        ),
        migrations.RemoveField(
            model_name='staffadmin',
            name='state',
        ),
        migrations.RemoveField(
            model_name='staffadmin',
            name='username',
        ),
        migrations.AddField(
            model_name='alllog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffadmin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffadmin',
            name='can_aadharcard',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='staffadmin',
            name='can_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffadmin',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
