# Generated by Django 4.2 on 2026-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0005_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='service_category/')),
                ('prod_cate', models.CharField(max_length=255)),
                ('sub_cate', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
