# Generated by Django 4.2 on 2026-02-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0007_vendorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spindoapp.vendor', to_field='unique_id'),
        ),
    ]
