# Generated by Django 4.2 on 2026-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0009_customerissue_staffissue_registeredcustomer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('vendor_id', models.CharField(blank=True, max_length=70, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=80, null=True)),
                ('cust_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('service_type', models.CharField(blank=True, max_length=30, null=True)),
                ('service_des', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_pdf', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
