# Generated by Django 4.2 on 2026-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0010_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='bill_date',
        ),
        migrations.AddField(
            model_name='billing',
            name='bill_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
