# Generated by Django 4.2 on 2026-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0011_remove_billing_bill_date_billing_bill_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
