# Generated by Django 4.2 on 2026-02-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0012_alter_billing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffadmin',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
    ]
