# Generated by Django 4.2 on 2026-02-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0013_staffadmin_staff_image_vendor_vendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
