# Generated by Django 4.2 on 2026-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0014_billing_bill_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestbyuser',
            name='request_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
