# Generated by Django 4.2 on 2026-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0016_contactus_rename_remarks_vendorrequest_extra_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllog',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='alllog',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staffadmin', 'Staff Admin'), ('vendor', 'Vendor')], max_length=50),
        ),
    ]
