# Generated by Django 4.2 on 2026-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0018_companydetailsitem_phoneotp_solarinstallationquery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bill_date_time',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bill_items',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bill_pdf',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='cust_mobile',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='service_des',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_payment',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='address_1',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='address_2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='address_3',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='amount_in_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='authorized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='bank_detail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='bill_item',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='buyer_ord_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='dated_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='dated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='del_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='delv_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='dispatch_doc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='invoice_no',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billing',
            name='mode_of_pay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='other_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='ref_no_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
