# Generated by Django 4.2 on 2026-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0019_remove_billing_amount_remove_billing_bill_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='status',
        ),
    ]
