# Generated by Django 4.2 on 2026-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0020_remove_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
