# Generated by Django 4.2 on 2026-02-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spindoapp', '0021_billing_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
